using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace WpfDataGridRandomColumnsBinding
{
    public partial class CustomDataGrid : DataGrid
    {
        public static readonly DependencyProperty BindableColumnsProperty = DependencyProperty.Register("BindableColumns", typeof(ObservableCollection<DataGridColumn>), typeof(CustomDataGrid), new PropertyMetadata(null));

        public ObservableCollection<DataGridColumn> BindableColumns
        {
            get => (ObservableCollection<DataGridColumn>)this.GetValue(BindableColumnsProperty);
            set => this.SetValue(BindableColumnsProperty, value);
        }

        protected override void OnAutoGeneratedColumns(EventArgs e)
        {
            if(BindableColumns != null && BindableColumns.Count > 0)
            {
                this.Columns.Clear();

                foreach (var item in BindableColumns)
                {
                    this.Columns.Add(item);
                }
            }
            else
            {
                base.OnAutoGeneratedColumns(e);   
            }
        }
    }
}
